// <auto-generated />
using Edux.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage;
using Microsoft.EntityFrameworkCore.Storage.Internal;
using System;

namespace Edux.Migrations.HostDb
{
    [DbContext(typeof(HostDbContext))]
    partial class HostDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.0.0-rtm-26452")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Edux.Models.AppTenant", b =>
                {
                    b.Property<string>("AppTenantId")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("ConnectionString");

                    b.Property<DateTime>("CreateDate");

                    b.Property<string>("Folder")
                        .HasMaxLength(200);

                    b.Property<string>("Hostname");

                    b.Property<string>("Name");

                    b.Property<string>("OwnerUserName")
                        .HasMaxLength(200);

                    b.Property<bool>("RequireSSL");

                    b.Property<long>("ThemeId");

                    b.Property<string>("ThemeName");

                    b.Property<string>("Title");

                    b.Property<DateTime?>("TrialEndDate");

                    b.HasKey("AppTenantId");

                    b.HasIndex("ThemeId");

                    b.ToTable("AppTenants");
                });

            modelBuilder.Entity("Edux.Models.Theme", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("ComponentTemplates");

                    b.Property<DateTime>("CreateDate");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasMaxLength(200);

                    b.Property<string>("CustomCSS");

                    b.Property<string>("Description");

                    b.Property<string>("ImageUrl");

                    b.Property<string>("Logo");

                    b.Property<string>("ManyLocation");

                    b.Property<string>("MenuLocations");

                    b.Property<string>("MetaDescription");

                    b.Property<string>("MetaKeywords");

                    b.Property<string>("MetaTitle")
                        .HasMaxLength(200);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200);

                    b.Property<string>("PageTemplates");

                    b.Property<DateTime>("UpdateDate");

                    b.Property<string>("UpdatedBy")
                        .IsRequired()
                        .HasMaxLength(200);

                    b.HasKey("Id");

                    b.ToTable("Themes");
                });

            modelBuilder.Entity("Edux.Models.AppTenant", b =>
                {
                    b.HasOne("Edux.Models.Theme", "Theme")
                        .WithMany()
                        .HasForeignKey("ThemeId")
                        .OnDelete(DeleteBehavior.Cascade);
                });
#pragma warning restore 612, 618
        }
    }
}
